### ISSUE TITLE
Character management seems to be broken

### ISSUE THREAD

**Issue by Riosodu** [alessio29/savagebot#104]
Everytime I do a command that interacts with some character I get a null error. 

`@Gabriel (Rio) Error while executing command !st. Details: null`

Chars are also being created, even though the null error.  It appears that the command is in fact being executed. If I apply a stun and check on `!list`, the char is stunned. All commands that are character related seems to act in the same way. 

Commands that I checked:
`!give`: null but applies
`!status`: null but applies
`!round`: doesn't create chars, the bot reply nothing, even though a new round is counted
`!remove`: null but applies
`!card`: bot doesn't reply, but char gets a new card
`!di`: create and deal only to the first character

**Comment by alessio29** [comment]
Fixed
