### ISSUE TITLE
Can Fatigue and wound tracking be done? Adding Multiple enemies with same card

### ISSUE THREAD

**Issue by beldar1215** [alessio29/savagebot#112]
Is there a way to track fatigue and wounds? I did not see a way to do this.
Also is there a way to add multiple enemies and have them all have the same card?

**Comment by alessio29** [comment]
Fatigue and wounds are not implemented at the moment.
To give one card to multiple enemies - create character named 'Enemies' (or 'Thugs', or whatever)
