### ISSUE TITLE
melee raise tracking

### ISSUE THREAD

**Issue by TheCastleKeeper** [alessio29/savagebot#115]
I don't see a way to change the Initial hit number and then 4 above for raises in the current version.  It's very much standard to have a target with a parry of 6 or 7, instead of a fixed 4 as it is now.  So we should be able to do something like !s8t7 or the like and have it show a hit at 7, and then a raise at 11, 15, 19, etc.  As it is right now, you have to do !s8-3 to get the same results.

Thanks

**Comment by alessio29** [comment]
This is already imlemented exactly this way: just try !s8t5.

Good luck
