### ISSUE TITLE
Give/Take Tokens from all characters

### ISSUE THREAD

**Issue by airespenlaw** [alessio29/savagebot#125]
My group just encountered this tonight. I misremembered seeing a "!give all" command, which lead to the attached exchange and much headdesking. Granted, the source of the problem was my giving bad commands, but some functionality to mitigate this would be useful.

![Savage Bot Give All](https://user-images.githubusercontent.com/64380668/80319702-c9cd9c80-8809-11ea-85b2-37648b12445a.png)

**Comment by alessio29** [comment]
I have removed chance of adding character named all
