### ISSUE TITLE
Bennies color

### ISSUE THREAD

**Issue by Bombhurr** [alessio29/savagebot#132]
The actual BENNIES category do not allow us to know which colors are the given bennies. 

!clearbennies <character1_name>/all [<character2_name>]; aliases: !cb
!givebenny <character_name> [<amount>]; aliases: !gb
!takebenny <character_name>; aliases: !tb

The former one was actually doing it 
!benny <character_name>
!hat [fill]
!pocket <character_name>
!use <benny_color> <character_name>

The !benny X was giving us the info :  _X got from hat **WHITE** benny for X_
And the !pocket X was giving us the info too : _X has in his pocket 2 white, 1 red, 0 blue and 0 golden benny(ies)_

Now the !gb X is giving us : _Given bennies to character(s): 1 to X_
And the !list is only telling us that X has 1 benny

Is there a way to know the actual bennies color (it is required at least for Deadlands reloaded as far as I know) ?

Anyway thanks for your work, it is very usefull.

**Comment by alessio29** [comment]
From now on SavageBot supports both normal bennies and Deadlands Reloaded bennies (colored version). 

To switch between them - use command `setbennymode` with 1 parameter: either 'normal' or 'deadlands'. 

`givebenny` command now supports colored bennies - to specify color use first letter: 'w' for white, 'b' for blue, 'r' for red and 'g' for golden.
Example: `!gb Ellie 2w` - gives 2 white bennies to character Ellie. 
You may omit number: `!gb Billy b` - character Billy gets 1 blue benny.

`clearbennies` clears all bennies at once 

`initbennies` (or `ib` for short) - initializes benny pool with 20 white, 10 red and 5 blue bennies

`pullbenny` (`pb`) - pulls benny from pool and gives it to specified character
Example: `!pb Louie 3` - pulls 3 bennies and gives to character Louie

`takebenny` (`tb`) takes benny from character
In normal mode you specify only character name: `tb Louie`
In deadlands mode you must also specify type of benny (w/b/g/r): `tb Louie w`

This version may still have some issues - feel free to tell if you encounter any.
