### ISSUE TITLE
Bot is down

### ISSUE THREAD

**Issue by PythonApprenticeGuy** [alessio29/savagebot#139]
Hello, been using the bot this past moths and have become a fan of it. However during last week session the bot was down and we had to user another one not designed for the savage worlds system. The bot is still down this week though. Would love for it to be up and running as soon as possible specially mid-Pandemic.

**Comment by alessio29** [comment]
Please use Reserve, invite link is: https://discord.com/api/oauth2/authorize?client_id=716426194509234178&permissions=0&scope=bot

I'm dealing with Discord support to get main bot back online.
