### ISSUE TITLE
Option to restrict max # of dice

### ISSUE THREAD

**Issue by bschollnick** [alessio29/savagebot#141]
One of my players decided to do:

!100000d6, which has continued to run for ~5-10 minutes...  

1) Can an option be added to restrict the max number of dice to be rolled at any one time?
2) An kill command to forcible stop the dice rolling?

Thanks.

**Comment by bschollnick** [comment]
![image](https://user-images.githubusercontent.com/979558/85213676-7ff7c300-b32f-11ea-9279-52bffe644cd9.png)

**Comment by alessio29** [comment]
Limit implemented
