### ISSUE TITLE
bot hacked

### ISSUE THREAD

**Issue by Almenon** [alessio29/savagebot#142]
I received a _extremely_ racist message from the bot on 05/30/2020. Any idea how this happened?

```
 HACKED BY GLENN BOT LIST AND ADVAITH @everyone ADD YOUR BOT TODAY AT https://glennbotlist.xyz/ https://discord.gg/QeaNNRW FREE NITRO 
Extremely racist message here....
 https://twitter.com/UGXDamage 
```

**Comment by Almenon** [comment]
I'm part of the Charisma Bonus channel which I think the bot used to be running in. The bot was removed from the channel.

**Comment by alessio29** [comment]
It took quite a time for you to get here. 
Password was compromised. Problem resolved.
