### ISSUE TITLE
Bot was hacked

### ISSUE THREAD

**Issue by beldar1215** [alessio29/savagebot#143]
I'm seeing the attached direct message from the bot.

![Savagebot](https://user-images.githubusercontent.com/25110714/89476766-c91d9e00-d748-11ea-9822-fc081da25c16.JPG)

**Comment by alessio29** [comment]
Fixed already

**Comment by KwalityCantrol** [comment]
The problem is that message appears immediately in a message from savagebot even though the date is 5/30.  I saw this today on a fresh install.
