### ISSUE TITLE
Bot no longer responds after '!prefix [' command

### ISSUE THREAD

**Issue by YggBjorn** [alessio29/savagebot#153]
I installed it and since I have carl-bot installed I changed the prefix for Savage Bot. 
It is no longer recognizing any commands. The last command it recognized was '!prefix [' but won't respond to '[ping' or '[help' or anything else, including '!ping'.
I tried kicking and re-inviting the bot but it still doesn't recognize the standard prefix or the new prefix.

**Comment by YggBjorn** [comment]
No response. That is unfortunate. My only recourse is to kick the bot seeing as it is useless for me now.

**Comment by alessio29** [comment]
I've deleted prefix '[' from database and added this to restricted prefixes.
