### ISSUE TITLE
!tb instruction not working to take multiple bennies

### ISSUE THREAD

**Issue by GuidoSarg** [alessio29/savagebot#158]
The !tb instruction is not taking multiple bennies when a participant names is appended with a number, and also appears to be ignoring anything after the first participant in the string.

If Huey Louie Dewey are given three bennies each, running the script below from the guidance only takes one bennie from Huey

!tb Huey Louie 2 Dewey 2

**Comment by alessio29** [comment]
Not intented to previously. 

Still it is implemented now and will be deployed in next couple of days. 
Issue closed.
