### ISSUE TITLE
Rolling a wildcard d1 causes a java heap space error

### ISSUE THREAD

**Issue by DagobertDev** [alessio29/savagebot#160]
Rolling a wildcard d1 with `!e1` leads to a memory overflow. 
I guess it's the users own fault to do this, but it might still be good to catch that.

![grafik](https://user-images.githubusercontent.com/34075591/111803622-7eaff280-88cf-11eb-8c47-6422ca9ac393.png)

**Comment by alessio29** [comment]
Fixed
