### ISSUE TITLE
!tb command asking for benny type to give

### ISSUE THREAD

**Issue by airespenlaw** [alessio29/savagebot#164]
When I used the Take Benny (!tb) command to take a benny last fortnight, it worked fine, but I used it yesterday and the bot asked me to provide a benny type to _give._ The bennies were neither taken from nor given to the character. 

![Savagebot Bug](https://user-images.githubusercontent.com/64380668/112771359-589ef680-9023-11eb-9545-37cd74b8e854.PNG)

**Comment by alessio29** [comment]
Fixed
