### ISSUE TITLE
Changing prefix

### ISSUE THREAD

**Issue by toddmoonbounce** [alessio29/savagebot#168]
Changing the bot prefix changes it for the specific Discord user/account only and this carries across ALL servers using the bot. The ideal function would be to change it for the specific server only and for all users. This way, the prefix is consistent PER server.

**Comment by alessio29** [comment]
You can use mention: **@SavageBot <command>** without any prefixes.

**Comment by toddmoonbounce** [comment]
Good to have the workaround but it's quite cumbersome in use.

Is it not possible to change how prefix edits work? Have them apply to a server rather than user? I'm in multiple servers with multiple bots along with this one and it causes lots of issues remembering what command lives where.
