### ISSUE TITLE
Reset the prefix

### ISSUE THREAD

**Issue by Lurius** [alessio29/savagebot#37]
Hi! Is there a way to reset the prefix? I changed it from ! to ?, but now the bot does not recognize the ? (or any other character for that matter). I must have set another prefix instead of ? by accident. I've tried to kick the bot and adding it again, but it does not help.
(reason for changing the prefix in the first place was having another bot with ! prefix)

**Comment by alessio29** [comment]
Hm..
Somehow missed this. 
Will look into at the evening.

**Comment by alessio29** [comment]
Well some prefixes (? ^ *) are bad (due to java specifics) - so I've prevented bot from setting these prefixes.
