### ISSUE TITLE
Tidy up the output (parentheses)

### ISSUE THREAD

**Issue by 9littlebees** [alessio29/savagebot#40]
No offense meant, but the output is quite ugly and not easy to read. Please look at some other dice bots for inspiration, or just use fewer parantheses.

Here is an idea for output which closely aligns with the current theme and could support any dice type:

[user] [custom text] - [dice roll]: [individual dice outputs separated by ` tags and spaces to make them stand out] = [result in bold]

See attached screenshot for how this looks in practice.

![Capture+_2019-07-08-10-11-48](https://user-images.githubusercontent.com/10364404/60793858-d690df00-a168-11e9-9786-6da8eff17bb8.png)

Alternatively, just put a hyphen after the custom text and lose the curly parentheses.

**Comment by alessio29** [comment]
Done
