### ISSUE TITLE
Bot avatar hard to see in dark mode

### ISSUE THREAD

**Issue by 9littlebees** [alessio29/savagebot#41]
Many, many people use Discord in dark mode. However the black logo is hard to see. Please consider doing something to make it visible for users using dark mode.

**Comment by 9littlebees** [comment]
I don't see any change in Discord - did you update the bot's avatar? If not, feel free to send me the PNG for the avatar, and I'd be happy to add a white glow around it for you in Photoshop.

**Comment by alessio29** [comment]
Yes, I've changed bot icor to to multi-colored one. As I can see right now - picture changed in web-client. May be you should restart discord client to see it.
