### ISSUE TITLE
Change Initiative modfiers to follow the rules

### ISSUE THREAD

**Issue by Necrotyr** [alessio29/savagebot#98]
Change the way quick and level headed works, so that the additional card for level headed are drawn first and then draw another card if none are above 5.

RAW in SWADE:
Characters with both the Level Headed and Quick Edges first draw their additional card and choose which to take. If that card is a Five or less, the Quick Edge may be used to draw a replacement until it’s Six or higher.

**Comment by alessio29** [comment]
Done
